version: '3.8'

services:
  dentisys-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dentisys-prod
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - dentisys-network

  dentisys-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dentisys-dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8082:8080"
    restart: unless-stopped
    networks:
      - dentisys-network

networks:
  dentisys-network:
    name: dentisys-network 