version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: bd-postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=sistemas2025
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    restart: unless-stopped
    networks:
      - dentisys-network

networks:
  dentisys-network:
    driver: bridge

volumes:
  postgres-data: 