[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "java -XX:+UseContainerSupport -XX:MaxRAMPercentage=75 -jar app.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3 

[deploy.env]
SPRING_PROFILES_ACTIVE = "prod" 